dist: trusty
language: node_js
node_js:
  - "10"
addons:
  sonarcloud:
    organization: "aaleksandrov"
#    token:
#      secure: "" # encrypted value of your token
script:
  - sonar-scanner
  - npm test
